### ISSUE TITLE
Crash on loading the book

### ISSUE THREAD

**Issue by Kostronor** [gigaherz/Guidebook#10]
Commit to add the book: https://github.com/Minecolonies/minecolonies/commit/c4eb3288bcb4318934caaea687cba6ef16175b02

Crash: https://gist.github.com/Kostronor/7c4b6f51f5d005cd2916d2cedeb32da8

**Comment by gigaherz** [comment]
Hmmm, yeah, something's null that should never be null. I want to get a release out over the weekend, so I'll fix this too.

**Comment by Kostronor** [comment]
Thanks! Just give me a ping when it's out and I retry!

**Comment by gigaherz** [comment]
I just noticed the log shows Guidebook 1.3.0, which is not the latest version. Does the crash happen with the latest? (1.7.0 is in review as I write this)
If it still crashes, feel free to reopen the issue or comment.
