### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Looodon** [gigaherz/Guidebook#108]
Hey, I'm on minecraft 1.19.2

I downloaded the mod, but when I follow the wiki and use the demobook it doesn't work. I followed the steps that said I had to add "demobook.xml" in "\.minecraft\config\books" and then add "demo.png" under "\.minecraft\config\books\resources."

Confusion:
- This command doesnt work "/give @p gbook:guidebook 1 0 {Book:"gbook:xml/demobook.xml"}" but when i use this command "/give @p gbook:guidebook{Book:"gbook:demobook.xml"} 1" i get a book that does nothing when I right click.
- I don't know if I have to include the books.JSON under "\.minecraft\config\books" too or not since I'm doing the config method, but even when I tried, it didn't work
- There has to be missing steps
EDIT: corrected the command

**Comment by gigaherz** [comment]
Just writing to say I have seen the issue and I keep the tab open, but I'm super busy with work.
