### ISSUE TITLE
1.19.2 resource pack doesn't work

### ISSUE THREAD

**Issue by huggger** [gigaherz/Guidebook#109]
As the title,I followed the method you given to create step by step,but it wasn't shown in game,I'd checked it out for many times but it was unusing either.I used command /give but I only got the "missing book".I'm sure the address was correct.
Didn't 1.19.2 version support resource packs?
(Even the example resource pack couldn't work...)

**Comment by gigaherz** [comment]
Hi the instructions may be outdated, but yes books in resource packs should work! If it doesn't work it's bug that I will have to fix.

Does your resource pack have a books.json file? and is the book xml with the right name and folder?

**Comment by huggger** [comment]
Hi,Yeah,I'm pretty sure.'Cuz I may wrong but example can't.
I enabled the example datapack and tried typing command /give @p gbook:guidebook{Book:"gbook:demobook.xml"} 1,but fact is,I got another "missing book"

**Comment by gigaherz** [comment]
I'll check when I get home.

**Comment by huggger** [comment]
got it,now I find I can edit guidebook.xml to get the book i want,But it's not convenient for true

**Comment by huggger** [comment]
hmmm...Have you found out the uncorrect places?

**Comment by gigaherz** [comment]
sorry I have become busy with christmas things. I will try to look as soon as I can but I can't promise when.

**Comment by huggger** [comment]
Don't be so worried,I'm just asking,have a nice christmas day btw.

**Comment by huggger** [comment]
oh,sorry that it's my bad,I put it into the datapacks folder instead of resourcepacks,it should be in resourcepacks one...
Nothing wrong with your mod in 1.19.2,sorry again about wasting your spare time
