### ISSUE TITLE
Images not displaying.

### ISSUE THREAD

**Issue by Wissi** [gigaherz/Guidebook#11]
Tried placing any custom image in:   
(apparently it's the default location for them to be recognized and pulled from)
/config/books/resources/

Also tried:
/config/books/
/config/books/resources/textures

Not even using an extracted minecraft "coal" image.

Only when pulled from default: 
```
<image src="minecraft:items/coal" tw="16" th="16" />
<book title="Guidebook Manual" cover="gbook:covers/default" fontSize="0.6">
```
Will they display.
This is my XML file:
```
<book title="image Test" cover="coal" fontSize="0.6">

  <include ref="standard.xml" />

  <chapter>
    <page>
      <title>Test of Images</title>
      <p></p>
      <image src="coal" tw="16" th="16" />
      <p></p>
      <p></p>
      <image src="/config/books/resources/coal" tw="16" th="16" />
      <p></p>
      <p></p>
      <image src="/config/books/coal" tw="16" th="16" />
      <p></p>
      <p></p>
      <image src="/config/books/resources/textures/coal" tw="16" th="16" />
      <p></p>
      <p></p>
      <image src="minecraft:items/coal" tw="16" th="16" />
    </page>
  </chapter>
</book>
```
![image_test1](https://cloud.githubusercontent.com/assets/23312242/26756603/0117f0c2-486c-11e7-89c7-10622f127580.png)

**Comment by gigaherz** [comment]
The format for the resources is "gbook:XYZ" which maps to
config/books/resources/textures/XYZ.png

The nam should be lowercase, and can reference subfolders.

**Comment by Wissi** [comment]
Thank you so much, small detail, HUGE difference. Maybe add it in Wiki? 
Working perfect now.
