### ISSUE TITLE
1.12.2 Game Crash on Initilization

### ISSUE THREAD

**Issue by Jayray538** [gigaherz/Guidebook#110]
I've looked around so much that I feel like I'm starting to learn Java. For some reason, I can't find a solution that works. Playing around a bit with my mod list fixed it for a time, but it just starting happening again. All that I changed as far as I know was I reactivated Astral Sorcery and Minecolonies, but the issue persisted even after deactivating them. I hate to beat a dead horse, as I'm sure this issue has been solved already, but some help would be very much appreciated.

Crash log:
[crash-2023-02-27_22.47.27-client.txt](https://github.com/gigaherz/Guidebook/files/10853935/crash-2023-02-27_22.47.27-client.txt)

**Comment by gigaherz** [comment]
This error is not actually in guidebook, but rather in a fork of guidebook that some mod includes. 

Try adding this to your mods folder (unzip, I can't post a .jar file to github comments): [gigaherz.Commons-1.12.1-0.6.4.zip](https://github.com/gigaherz/Guidebook/files/10853975/gigaherz.Commons-1.12.1-0.6.4.zip)

The other solution is to remove the guidebook file from the memory_repo folder, but that will re-appear any time you enable that mod.

**Comment by Jayray538** [comment]
Dear Jesus, I could kiss you right now! I appreciate the quick response my friend, even though I'm about a year late LOL. If you don't mind my asking, what changed by adding that jar to my mods folder, and how did you know?

**Comment by gigaherz** [comment]
So, back in 1.12, I was using the "jar in jar" feature to embed my utility library (gigaherz commons) in my mods. Some mod asked me if they could fork guidebook for their needs, and I OKd, but later I started getting reports about crashing. 
I recognized the missing class in the log, and guessed that they embedded a version of guidebook that was built without the commons library, so those utility classes are missing.

**Comment by Jayray538** [comment]
Gotcha! That makes a lot of sense. Thanks for explaining it to me, I'm trying to learn a little bit here and there so I don't have to bother mod authors as much lol. Your solution worked, and I greatly appreciate your time and expertise. I wish you a wonderful day c:
