### ISSUE TITLE
[1.19.3] Tags defined by templates considered undefined

### ISSUE THREAD

**Issue by XFactHD** [gigaherz/Guidebook#112]
When loading into a world, the log complains about certain tags being undefined. All tags it complains about are defined via the `gbook:xml/standard.xml` template library:
```
[01:35:26] [Render thread/WARN] [gbook/]: Unrecognized tag: page_title
[01:35:26] [Render thread/WARN] [gbook/]: Unrecognized tag: divider
[01:35:26] [Render thread/WARN] [gbook/]: Unrecognized tag: big_recipe
```

The `page_title` element for example therefore doesn't work in-game, leading to all pages in the example book missing titles.

Forge: 1.19.3-44.1.0
Guidebook: Guidebook-1.19.3-3.7.1

**Comment by gigaherz** [comment]
Oops didn't notice that. Looking into it.

**Comment by gigaherz** [comment]
v3.7.2 should fix this.

**Comment by XFactHD** [comment]
Yup, works as expected now
