### ISSUE TITLE
[1.19.3] Book model transform issues

### ISSUE THREAD

**Issue by XFactHD** [gigaherz/Guidebook#114]
The book model is very large in third person and on the ground and clips through the player's hands and the ground
![grafik](https://user-images.githubusercontent.com/11262040/223811598-8d537a2c-3ddd-434f-b511-57569c9292ce.png)

The book points the wrong way when placed in an item frame, hiding the cover
![grafik](https://user-images.githubusercontent.com/11262040/223810348-debcb2db-5f83-4c69-b8c9-0ecf97b2d16b.png)

Forge: 1.19.3-44.1.0
Guidebook: Guidebook-1.19.3-3.7.2

**Comment by gigaherz** [comment]
So, apparently in 1.19.3 the models don't seem to inherit the parent model "display" transforms. May or may not have been a bug in 1.19.2 also. Would need to check. Copypasting the transforms from the parent fixes this... 🤔

**Comment by gigaherz** [comment]
Should be fixed (worked around) as of 3.7.3
