### ISSUE TITLE
[1.20.1] Spacing not working

### ISSUE THREAD

**Issue by thiakil** [gigaherz/Guidebook#116]
![image](https://github.com/gigaherz/Guidebook/assets/1788847/96de966a-1563-4d00-9b4d-338d9ec58ff8)

The  `<space height="33%"/>` doesn't appear to be working

**Comment by gigaherz** [comment]
I'll look into it as soon as I can

**Comment by gigaherz** [comment]
I have fixed the bug, but in fixing it I noticed that templates are not substituting correctly so it will take a bit longer to get a new version out.

**Comment by thiakil** [comment]
_poke_

**Comment by gigaherz** [comment]
Oh shit I completely forgot about this... No idea what state it's in, let me go look. XD

**Comment by thiakil** [comment]
woo, thanks!
