### ISSUE TITLE
[1.20.1] Cross-mod issue with Sawmill. ("invalid player data" disconnect when joining a server.)

### ISSUE THREAD

**Issue by Gbergz** [gigaherz/Guidebook#118]
## Info
When joining a server you get disconnected with the following message "Invalid Player Data":
![ss](https://github.com/gigaherz/Guidebook/assets/26634554/28b4b915-0cff-437e-9ad4-e7a46e94fb7b)

This issue started happening with a more recent version of the Sawmill mod.
If I roll back to the version 1.2.4 of Sawmill, the issue no longer occurs.

This issue only happens on a server. Singleplayer is fine.

## Other Info
(Modpack: TNP Limitless 7).

Originally reported this here, which lead me here since it is apparently caused by the Guidebook mod.
https://github.com/MehVahdJukaar/sawmill/issues/39

Sawmill project page:
https://legacy.curseforge.com/minecraft/mc-mods/sawmill

## Versions
MC: 1.20.1
Forge: 47.2.17
Guidebook: 3.8.2
Sawmill: 1.3.13

## Log:
https://gist.githubusercontent.com/Gbergz/3f8f2649f61a9ffc322872d945047842/raw/8528b50bb039c7f4baeb15f31861cf95eba779f7/gistfile1.txt

**-** Gbergz

**Comment by gigaherz** [comment]
It appears the sawmill mod is causing forge to enumerate the creative tab contents in the server side, but Guidebook doesn't support this.
I'll have to add a check to ensure my logic doesn't run in the server.

**Comment by gigaherz** [comment]
I have uploaded a bugfix, version 1.20.1-3.8.3 which is currently waiting for review by curseforge and should be available in a few minutes. It is untested but I hope it is enough to fix the crash.

**Comment by Gbergz** [comment]
Awesome, and thanks. I will test this asap tomorrow! 👍

**Comment by Gbergz** [comment]
Confirmed fixed. 

Thanks! 👍
