### ISSUE TITLE
Gradle can't load it on 1.10

### ISSUE THREAD

**Issue by Raycoms** [gigaherz/Guidebook#13]
I have:

    deobfCompile "gigaherz.guidebook:Guidebook-1.10.2-1.6.0"

and

maven {
        url 'http://dogforce-games.com/maven'
    }

Isn't the 1.10 added to the dogforce maven repository?

**Comment by gigaherz** [comment]
it's "gigaherz.guidebook:Guidebook-1.10.2:1.6.0'

**Comment by Raycoms** [comment]
Do you know a way how I can solve this?

2017-06-10 17:43 GMT-03:00 David Quintana <notifications@github.com>:
