### ISSUE TITLE
Problem with tconstruct compatability

### ISSUE THREAD

**Issue by Raycoms** [gigaherz/Guidebook#15]
Getting this when trying to start the game:

> [10:03:43] [Client thread/ERROR] [FML]: Caught exception from tconstruct
> java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.clamp(FFF)F
> 	at slimeknights.tconstruct.library.client.CustomFontColor.valueToColorCode(CustomFontColor.java:45) ~[TConstruct-1.10.2-2.6.5.9.jar:?]
> 	at slimeknights.tconstruct.library.materials.HeadMaterialStats.<clinit>(HeadMaterialStats.java:29) ~[TConstruct-1.10.2-2.6.5.9.jar:?]
> 	at slimeknights.tconstruct.library.materials.Material.<clinit>(Material.java:62) ~[TConstruct-1.10.2-2.6.5.9.jar:?]
> 	at slimeknights.tconstruct.tools.TinkerMaterials.mat(TinkerMaterials.java:128) ~[TConstruct-1.10.2-2.6.5.9.jar:?]
> 	at slimeknights.tconstruct.tools.TinkerMaterials.<clinit>(TinkerMaterials.java:68) ~[TConstruct-1.10.2-2.6.5.9.jar:?]
> 	at slimeknights.tconstruct.shared.TinkerFluids.setupFluids(TinkerFluids.java:85) ~[TConstruct-1.10.2-2.6.5.9.jar:?]
> 	at slimeknights.tconstruct.shared.TinkerFluids.<clinit>(TinkerFluids.java:77) ~[TConstruct-1.10.2-2.6.5.9.jar:?]
> 	at slimeknights.tconstruct.TConstruct.<clinit>(TConstruct.java:100) ~[TConstruct-1.10.2-2.6.5.9.jar:?]
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
> 	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
> 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:507) ~[forgeSrc-1.10.2-12.18.2.2115-PROJECT(minecolonies).jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[forgeSrc-1.10.2-12.18.2.2115-PROJECT(minecolonies).jar:?]
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[forgeSrc-1.10.2-12.18.2.2115-PROJECT(minecolonies).jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
> 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549) [Loader.class:?]
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218) [FMLClientHandler.class:?]
> 	at net.minecraft.client.Minecraft.startGame(Minecraft.java:477) [Minecraft.class:?]
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:386) [Minecraft.class:?]
> 	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
> 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
> 	at GradleStart.main(GradleStart.java:26) [start/:?]
> [10:03:43] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:649]: ---- Minecraft Crash Report ----
> // I'm sorry, Dave.
> 
> Time: 6/4/17 10:03 AM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.clamp(FFF)F
> 	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
> 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:580)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
> 	at net.minecraft.client.Minecraft.startGame(Minecraft.java:477)
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:386)
> 	at net.minecraft.client.main.Main.main(Main.java:118)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
> 	at GradleStart.main(GradleStart.java:26)
> Caused by: java.lang.NoSuchMethodError: net.minecraft.util.math.MathHelper.clamp(FFF)F
> 	at slimeknights.tconstruct.library.client.CustomFontColor.valueToColorCode(CustomFontColor.java:45)
> 	at slimeknights.tconstruct.library.materials.HeadMaterialStats.<clinit>(HeadMaterialStats.java:29)
> 	at slimeknights.tconstruct.library.materials.Material.<clinit>(Material.java:62)
> 	at slimeknights.tconstruct.tools.TinkerMaterials.mat(TinkerMaterials.java:128)
> 	at slimeknights.tconstruct.tools.TinkerMaterials.<clinit>(TinkerMaterials.java:68)
> 	at slimeknights.tconstruct.shared.TinkerFluids.setupFluids(TinkerFluids.java:85)
> 	at slimeknights.tconstruct.shared.TinkerFluids.<clinit>(TinkerFluids.java:77)
> 	at slimeknights.tconstruct.TConstruct.<clinit>(TConstruct.java:100)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:507)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
> 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549)
> 	... 16 more
>

**Comment by Wissi** [comment]
Do you require more info for this issue? So we can provide it.

Thanks.

**Comment by gigaherz** [comment]
Hmm I seem to have missed this...

It does not look like it would be my fault... the stack trace does not mention Guidebook in any way, and the missing method is in Minecraft itself... are you certain this issue is caused by Guidebook?

**Comment by Raycoms** [comment]
This only happens when I add Guidebook and the guideBook repo to the
dependencies in gradle.

2017-06-07 18:03 GMT-03:00 David Quintana <notifications@github.com>:

**Comment by gigaherz** [comment]
It is very strange, then, since I don't even call that method at all, in Guidebook, and loading my development environment with TiCon in he mods folder, works just fine...

Could you provide mode information about your setup? It really feels like a version mismatch somehow (like if you are loading 1.11 TiCon in 1.10 or so)

**Comment by gigaherz** [comment]
Another thought: that stack trace could also happen if you use a deobf/dev jar from ticon, which was compiled with different mappings than the ones you have in your build.gradle. It may be best if you take a non-dev jar and deobfuscate it yourself (BON2 or forgegradle's deobfCompile if they have a maven)...

**Comment by Raycoms** [comment]
I use these here as dependencies additionally.

deobfCompile "slimeknights.mantle:Mantle:1.10.2-1.1.5.205"
deobfCompile "slimeknights:TConstruct:1.10.2-2.6.3.500"



repositories {
    maven {
        name 'DVS1 Maven FS'
        url 'http://dvs1.progwml6.com/files/maven'
    }
}


2017-06-07 18:14 GMT-03:00 David Quintana <notifications@github.com>:

**Comment by gigaherz** [comment]
I can't reproduce this, and I really don't think it's Guidebook's fault, so I'm going to dismiss it as a configuration problem on your end. My best guess would be incompatible mappings. Try to use mappings="stable_29" on your project, and see if that fixes it.
