### ISSUE TITLE
[1.11.2][1.7.0]Compatibility issue between Guidebook and EZstorage, may include other inventories

### ISSUE THREAD

**Issue by Rosethorns** [gigaherz/Guidebook#18]
Unknown what precisely causes this but it has to do with the EZStorage system either containing a guide and it being removed, or the guide being added into the inventory and then a crafting event following soon after. And pretty much anything inbetween.

Here is a pastebin of the issue.

https://pastebin.com/Dd4ihVGz

**Comment by Necr0** [comment]
There's something weird going on there. It says `BookRegistry` is not defined even though it should be. Even though it's in client there is nothing stripping the class, meaning no `@SideOnly` annotation or sth. And also even if the error should occur it should be handled by [EZStorage's method](https://github.com/zerofall/EZStorage2/blob/master/src/main/java/com/zerofall/ezstorage/util/EZStorageUtils.java#L44-L48), and because of a dated version or sth either because it already caught exceptions when it was first introduced. The class maybe wasn't referred to in the code before so maybe it isn't loaded but even if that's the case the JVM should just load it when it's first referenced. I honestly do not know about this one, sorry. I guess, @gigaherz needs to look into this.

**Comment by gigaherz** [comment]
EZStorage is calling ItemStack.getDisplayName from the server. This is not recommended, because the server can't load mod translations, but my mod shouldn't crash from it. I'll work around that when I get home.

**Comment by Rosethorns** [comment]
Hi Gigaherz,

Forge: 13.20.0.2315
EZStorage 2: 2.4.1

As with you, I have not been able to cause the crash myself. This was caused by one of my players. And the player can repeat the crash without fail just by having my guidebook present in some capacity while using his EZstorage setup.

Its incredibly strange as I have been personally supervising him when he causes it as part of trying to nail down the exact catalyst for it. And. We still don't know.

On the exact same server, using his setup. I cannot cause the issue myself which to me says the missing link has something to do with him? his connection?

He doesn't use optifine. And you can see the full mod list here.
https://minecraft.curseforge.com/projects/raxpack-2/relations/dependencies

**Comment by gigaherz** [comment]
Has he tried to reinstall the pack, or at least the mod jar? Is he using any custom mods in the client?

**Comment by Rosethorns** [comment]
Actually now that you mention it I believe he said he is using Dynamic Surroundings. But I'm not sure how that would interact in this case?

I'll ask him to remove it and then see if he can cause the crash again.

**Comment by Rosethorns** [comment]
Can confirm with a completely new profile of the instance that they can still cause the crash.

**Comment by Rosethorns** [comment]
Okay,

With a great sigh of relief I can finally say that we have uncovered how to cause the glitch 100% of the time.
On a server:
1: have a storage core with at least 1 attached storage block so that you have a functioning EZstore
2: place any other item into the system. You need at least 1 other item in the system.
3: add the guide book to the system.
4: close the gui.
5: try to access the system again.

By step 5 you should find that you are desynced with the world and can no longer interact with in world objects. The world should still be functional however.

With the guidebook still in the system you should crash the server if you log out.

Notes:
If one person puts the book into the system causing themselves to desync, another player can then remove the book from the system causing both the original player and the server to return to normal and so no longer cause a crash now that the book is removed.

If the second player accesses the system without removing the book. Then they too become desynced.

the mechanism for the crash seems to entirely revolve around the player accessing a EZstorage system that contains a guide book + items. If they system no longer contains a guide book there will be no crash.

If the system contains ONLY the guidebook, there will be no crash.


I really hope this helps. Let me know if this is on EZStorages end and I will cross reference this issue with them

**Comment by gigaherz** [comment]
Hopefully v1.7.3 fixes the issue. It's being reviewed at curseforge as I write this. Feel free to tell me if you can still experience it.
