### ISSUE TITLE
Could we get some wiki examples for mod pack authors? 

### ISSUE THREAD

**Issue by Winddbourne** [gigaherz/Guidebook#2]
Perhaps the Github wiki should include some examples of the setup. Using the in game book for version 1.10.2.1.3.3 is a bit confusing.

It seems to tell you to look in "Config/guidebook" for an example of a book resource pack. Yet that folder doesn't exist. Instead you find "Gbook.cfg" which (sort of) points you to a sub folder hidden inside the jar itself called "XML". 

Of course this makes sense if you have made resource packs before. Right now I'm assuming I need to make a folder called "Guidebook" and put the "XML" folder inside it and the mod will auto load my book with the pack. That is very convenient.

Unfortunately to figure that out I had to guess the missing parts of the resource file were pointing to assets being loaded by the mod and pry it open with 7zip to check. But what I found didn't match the instructions in the book. There was no Books.Json in the assets folder. So I downloaded ender-rift temporarily and pried that open too for comparison. 

I haven't tried writing up a sample book and testing my hypothesis yet but if that is how simple it is . . . it's a GREAT design . . . and my entire problem could have been solved by replacing the entry for "Configuration folder" with this text:

"Mod pack authors wishing to add books that can be made available to their players should create a new folder called "Config/Guidebook". If you place a properly formatted XML file here the guidebook mod will automatically load it into memory and register it as if it were a resource pack."

After that something about how to provide the book to the players would also be helpful. I'm assuming I need to create a recipe for it,  provide it using a starting inventory mod, or give it as a HQM quest reward. 

But it could also simply auto load into the players inventory which would be awkward should I be making multiple guides.

**Comment by forReason** [comment]
same request here. im currently thinking of adding minecolonies support

**Comment by gigaherz** [comment]
I have been sick the past few days, but I want to try to get something written over the weekend.

**Comment by gigaherz** [comment]
I have added wiki pages, with an improved version of the ingame manual.

https://github.com/gigaherz/Guidebook/wiki

I'm in the process of collecting screenshots for the wiki.

**Comment by gigaherz** [comment]
I have just released a new version, which adds the ability to configure a set of books to give players on first join (acts retroactively to give the same books to existing players that didn't get them yet).

I'm closing this since I believe I have addressed most of the points. If there's something else you'd want to see mentioned, feel free to tell me.
