### ISSUE TITLE
opengl error

### ISSUE THREAD

**Issue by PSILONCRAFT** [gigaherz/Guidebook#20]
Hi im using optifine with your mod and i get a openGL error 1281 error
![skjermbilde 2017-08-01 kl 13 10 09](https://user-images.githubusercontent.com/26674039/28822791-efb2ac8c-76ba-11e7-9cae-fdbe6897c62f.png)

this only happens when i have optifine running

**Comment by gigaherz** [comment]
Hello, I can't reproduce your error on my machine. What version of Guidebook are you trying? What version of Minecraft? Forge? What graphics card do you have? Are the drivers up to date?
