### ISSUE TITLE
img example in demobook.xml is wrong

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/Guidebook#26]
https://github.com/gigaherz/Guidebook/blob/master/examples/config/books/demobook.xml

in it you have

```<img src="domain:item" />```

however, the mod wants the ```<img>``` tag to be terminated with ```</img>``` and not ```/>```

**Comment by kreezxil** [comment]
sorry this was caused by invalid xml on my side it does want ```/>```

**Comment by gigaherz** [comment]
Good to know, because I use one of java's most used XML libraries, and if it didn't work it would mean the lib is broken. ;P
