### ISSUE TITLE
Need more nesting.

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/Guidebook#27]
```<link>``` and ```<image>``` tags need to be allowed to be nested inside of ```<p>``` blocks.

also could use additional tags for ```<b>```old, ```<i>```talics, and ```<u>```nderline, and they should also be allowed to be nested inside of the ```<p>``` blocks.

**Comment by gigaherz** [comment]
This is planned, but I have limited time right now. Along with <span> tags.

**Comment by kreezxil** [comment]
No, hurry, I'm just reported what I'm finding that you didn't mention was planned.

**Comment by kreezxil** [comment]
Btw, this is by far the easiest way I've seen to add a book.

**Comment by gigaherz** [comment]
I have released a brand-new (beta) version of Guidebook, which MAY break existing books, but among other things, it allows mixed nesting of text, spans (for formatting), stacks, and images, within p blocks.
You can find the beta release here: https://minecraft.curseforge.com/projects/guidebook/files/2518170
I do plan more improvements before I consider my v2.0 goals completed.
