### ISSUE TITLE
1.12.0-1.7.3 for 1.12.2 crashes Dedicated Server

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/Guidebook#28]
Issue:  1.12.0-1.7.3 crashes dedicated server Forge 1.12.2 build 2512

Notes:
     on startup while looking for clientside classes

crash report:
https://gist.github.com/d12b881dd53935991653a320c3374384

fml server latest:
https://gist.github.com/afbcb09692d761d34ed73a7700156de7

**Comment by gigaherz** [comment]
Wil fix as soon as I get home.

**Comment by Necr0** [comment]
Should already have been fixed in 41c545203cd259851a38a14e5af35ceb4504b238 . In other words: It the next release should fix this error. Until then you have to remove either CraftTweaker or the Guidebook mod as interaction of CraftTweaker with this mod causes the error.

**Comment by kreezxil** [comment]
sweet.

**Comment by gigaherz** [comment]
Hello, as I mentioned in #31, 
I have released a brand-new (beta) version of Guidebook, which MAY break existing books, but among other things, it should fix the crash. If it's really inconvenient I can release a final bugfix of the 1.x branch, but I would rather avoid that... :P
You can find the beta release here: https://minecraft.curseforge.com/projects/guidebook/files/2518170
