### ISSUE TITLE
Needs a better rendering size in Large GUI Size

### ISSUE THREAD

**Issue by NovaViper** [gigaherz/Guidebook#29]
For some reason, when I have the render size set to Large, the book gui is ended **EXTREMELY** small, to the point I can barely see it. This is especially bad for my 21" monitor. Every other gui, with the exception of RPG Hud, whom I have also contacted the author about, is rendered normally

**Comment by NovaViper** [comment]
Also, I went and removed every mod except this one and it is still scaled too small. There is something I noticed though, when I have the game not maximized (with both mods and no mods), it scales correctly.

**Comment by gigaherz** [comment]
Do you have a screenshot? I would like to see if I can reproduce what you see locally. Meanwhile, you can set the book gui scale to a custom value, to fit your needs, if my automatic value doesn't work for you.

**Comment by NovaViper** [comment]
Here ya go! Sorry for taking a while, I was trying to address another issue I was having with another custom book mod (the one where this was referenced to)
![2017-10-15_16 02 08](https://user-images.githubusercontent.com/7191115/31589156-61ef69d8-b1c2-11e7-8440-a9f340109f23.png)

**Comment by gigaherz** [comment]
Hello, I just uploaded v2.5 (highly experimental alpha, it's still under review but should be available soon), which among other things, has an improved logic for calculating the book scale. This issue should be fixed, but feel free to comment if you can still reproduce it!
