### ISSUE TITLE
Serverside Crash

### ISSUE THREAD

**Issue by Tetrajak** [gigaherz/Guidebook#31]
Minecraft Version: 1.12.2
Forge Build: 2555
Mod Version: 1.7.3
Crash Log: https://pastebin.com/aDD6spmz

The mod causes a server to crash while attempting to load.

**Comment by gigaherz** [comment]
I see, CraftTweaker is calling getSubItems on the server, but the mod was never tested after Forge made the function available server-side in 1.12.2. I'll fix as soon as I can.

**Comment by gigaherz** [comment]
Hello!
I have released a brand-new (beta) version of Guidebook, which MAY break existing books, but among other things, it should fix the crash. If it's really inconvenient I can release a final bugfix of the 1.x branch, but I would rather avoid that... :P
You can find the beta release here: https://minecraft.curseforge.com/projects/guidebook/files/2518170
