### ISSUE TITLE
Model for books not loading properly

### ISSUE THREAD

**Issue by PoroUsedSnax** [gigaherz/Guidebook#34]
So, I'm not sure if this could be an issue for me, or the mod, but in-game, the books don't have a model, as seen below:
![2018-02-14_19 56 52](https://user-images.githubusercontent.com/19329455/36225031-4f82c100-11c1-11e8-871f-0c3b4d84c176.png)
Currently using Minecraft 1.12.2, Forge 14.23.1.2604, and Guidebooks 2.0.0

There is an error loading the assets it needs, here: https://pastebin.com/8FPZyXYN

**Comment by Wissi** [comment]
Yeah, it's a well know Issue by Gigahertz;     (Quote from Github)
```
gigaherz
Posted Jul 7, 2017
Hmm you are right, the 1.12 version seems to be unable to load textures from the config folder. I'll try to figure out why.
```
We're waiting for him to figure out a workaround or fix, so i can update the config and book.

**Comment by gigaherz** [comment]
It is a separate issue. Seems like newer versions of forge cause the mod to be unable to load the model itself (instead of just the cover). I will get to it soon.

**Comment by gigaherz** [comment]
v2.0.1 is in review on curseforge and will be available shortly. Turns out I had already fixed the bug locally, I just forgot to release it.
