### ISSUE TITLE
Crash on Resource Pack changing(resource reload)

### ISSUE THREAD

**Issue by Xaikii** [gigaherz/Guidebook#38]
https://pastebin.com/bNUnLMTe

Versions:
guidebook-1.12.2-2.0.1
gigaherz.commons-1.12.1-0.6.4
MC Version 1.12.2
Forge 14.23.2.2652
Java 1.8.0_161

**Comment by gigaherz** [comment]
Any chance I can have a copy of the book that is being loaded, or some more information? The crash is somewhere that shouldn't be crashing, so that seems to me like something else is going wrong elsewhere, but I need to be able to reproduce the crash in order to track down where.

**Comment by Xaikii** [comment]
I think the only Books I have are from Rockhounding Chemistry and I am not sure prob. Blood Magic

**Comment by gigaherz** [comment]
Okay thanks, I'll take a look as soon as I can.
