### ISSUE TITLE
Copy to Clipboard

### ISSUE THREAD

**Issue by gdarai** [gigaherz/Guidebook#39]
Is there a tag for copying some text into the clipboard?
If not, please add it.

**Comment by gigaherz** [comment]
You mean like, when you click on a certain link, it copies to the clipboard?

**Comment by Necr0** [comment]
A way to go about implementing such a thing could be implementing some sort of action type system. What i mean is adding an "action"-attribute to link determining how what to do when the link is clicked. And then having some other attribute(s) as options for said action.
```
<link action="gbook:copy" data="text to copy to clipboard">copy some text to clipboard</link>
<link action="copy" target="element-id">copy text from element to clipboard</link>
<link action="gbook:command" data="spawnpoint">set spawnpoint to current position (requires op)</link>
```
The handler for said actions would probably just be give the link elements to read out the attributes by itself.

**Comment by gdarai** [comment]
Yes that is exactly what I am looking for.
The issue is that with such capability I would be able to give the player a way to get parts of the book and for example paste them into Open Computer command line... or into Minecraft Console.

**Comment by gigaherz** [comment]
Hmmm, how about a `<code>` type tag, that automatically places a "copy" icon next to the text?

I'm thinking like... 

Very quick&dirty mockup, just to get the idea:
![image](https://user-images.githubusercontent.com/685851/39663998-b9f790e8-507c-11e8-801a-6b9a8583119c.png)

I'm still recovering from having been sick lately, but I seem to be quite refreshed right now, so there's a lot I want to do, including easing myself back into modding...

**Comment by gdarai** [comment]
I also noticed, there is "Copy to Clipboard" inside the WEB link, but when you put there some other text, not the "link" but for example a wget command, the link stop working and the "Copy to Clipboard" is not available any more, so even to just make this work would be enough.

**Comment by gigaherz** [comment]
That dialog is vanilla, I just make use of it.

**Comment by gigaherz** [comment]
Went the easy route, in the end:
![book clicking link](https://i.imgur.com/jmDj5sP.jpg)
![text copied message](https://i.imgur.com/TivVOKO.jpg)
(The book doesn't close, but since the message appears behind the book, I closed it myself to show)

The corresponding XML for that link is:
`<link action="copyText" text="Text to copy to the clipboard">Click me 3</link>`

I have a couple more things to look at, but I will be releasing this soon.

**Comment by gigaherz** [comment]
v2.5.1 is out ans includes links that can copy to clipboard!
