### ISSUE TITLE
[Bug] - Recipe

### ISSUE THREAD

**Issue by forReason** [gigaherz/Guidebook#4]
When building a recipee many items are purple and black replacementgraphic.

also I want to insert bonemeal which is 351:15
but the text is minecraft:dye. It will just put some random dye or even coca beans in

**Comment by gigaherz** [comment]
Hey,

Do you have a code example for an item that shows the placeholder model?

For bonemeal, you have to use `<stack item="minecraft:dye" meta="15" count="1" />`.

**Comment by forReason** [comment]
thanks, this solved both problems. Issue was that I used the examplerecipee and thought "meta" contains an internal code where the item gets placed in the grid. therefore it was not able to find an image for `bucket:7` for example

```
<big_recipe>
        <stack item="minecraft:stained_glass" meta="0" />
        <stack item="minecraft:stained_glass" meta="1" />
        <stack item="minecraft:stained_glass" meta="2" />
        <stack item="minecraft:stained_glass" meta="3" />
        <stack item="minecraft:stained_glass" meta="4" />
        <stack item="minecraft:stained_glass" meta="5" />
        <stack item="minecraft:stained_glass" meta="6" />
        <stack item="minecraft:stained_glass" meta="7" />
        <stack item="minecraft:stained_glass" meta="8" />
        <stack item="minecraft:stained_glass" meta="9" />
      </big_recipe>
```

**Comment by forReason** [comment]
[feature request] - unse an actual recipee in the example of the guidebook.xml
