### ISSUE TITLE
Release missing

### ISSUE THREAD

**Issue by Nightenom** [gigaherz/Guidebook#44]
Hello, release 2.0.1 is missing at http://dogforce-games.com/maven/gigaherz/guidebook/, therefore this version can't be used with gradle

**Comment by gigaherz** [comment]
Oops will upload asap.

**Comment by gigaherz** [comment]
Why can't you import my package? Even if you can't add it as a maven dependency, you can still load it as a fileTree dependency...

**Comment by Nightenom** [comment]
I finally got it, it's imported as a maven dependency, but this occurs while gradlew runClient with a mod, but not as the standalone mod, (also tested with locally compiled version of Guidebook)
[crash-2018-05-18_09.03.01-client.txt](https://github.com/gigaherz/Guidebook/files/2015902/crash-2018-05-18_09.03.01-client.txt)

**Comment by gigaherz** [comment]
I see, I believe that's because guidebook depends on `gigaherz.commons`, which I use in my own projects as a dependency, and I include as an embedded jar within the guidebook jar. You may need to add this dependency also:
`
    deobfCompile "gigaherz.commons:gigaherz.commons-1.12.1:0.6.4"
`

**Comment by Nightenom** [comment]
Good to go, hopefully, you will find some time to continue at this free time job.
Have a nice day :)
