### ISSUE TITLE
[2.5.1 and 2.5.2] Crash at server load (Exception in server tick loop)

### ISSUE THREAD

**Issue by Geethebluesky** [gigaherz/Guidebook#48]
Here's the [crash log](https://gist.github.com/Geethebluesky/ce672614de26dd4a6a93d792e348dac4). 

This happened when I updated Guidebook to v2.5.2 on my private server just now, up from 2.5.0.

The same crash happens [with v2.5.1](https://gist.github.com/Geethebluesky/aaf160b9a0aa755ff0f5a939b3097d10), which I'd skipped over by mistake.

Going back to 2.5.0 avoids this.

**Comment by gigaherz** [comment]
Hmpf.... the stack trace ends with `Caused by: java.lang.NullPointerException`, which doesn't tell me where the NPE happened. Can you look at the full log to see if you can obtain the complete stack trace?

**Comment by Geethebluesky** [comment]
1 min

**Comment by gigaherz** [comment]
Welp, that isn't really any more useful... >_<
Thing is, I have tested the mod locally, on both dev server+client, and non-dev server+client, and it didn't crash. Do you know which mod from your list is using guidebook?

My best guess for what is crashing would be that one of the mods is registering the BookRegistryEvent server-side, but it should only be registered in the client. But I have no idea if that's the case with that meaningless stack trace (not blaming you, just the stack trace is annoyingly unhelpful XD)

**Comment by Geethebluesky** [comment]
Oh in that case I'll bring this up with the author of the guidebook, there's only one so far. :) Thank you!

**Comment by gigaherz** [comment]
Okay thanks, I will implement a workaround in my mod regardless, to try to avoid loading the book registry in the server, just to make everyone's life simpler.

**Comment by gigaherz** [comment]
Hey if you want to test this new build 2.5.3, it might solve your crash: https://minecraft.curseforge.com/projects/guidebook/files/2573054

**Comment by gigaherz** [comment]
I'm assuming the crash is fixed, but feel free to comment if that's not the case and I will reopen.

**Comment by TheFloydman** [comment]
It wasn't a Side issue (LTTA kept crashing with 2.5.3), but I hadn't declared a dependency in my main class to make sure LTTA loads after Guidebook. LTTA was referencing a class that hadn't been loaded yet. Nothing wrong on your side, gigaherz.

**Comment by gigaherz** [comment]
Good to know! :)
