### ISSUE TITLE
"Centered" Text is Off-Center

### ISSUE THREAD

**Issue by TheFloydman** [gigaherz/Guidebook#50]
The new versions (2.5) are great! I'm loving the page numbers on every page and the new Home button. (Thank you!) I'm getting some weird artifacts on a couple of pages, though. I'll see if I can upload a couple of screenshots. Centered text on only 2 occasions is running off the page.
![2018-06-15_15 23 39](https://user-images.githubusercontent.com/22880199/41491966-02e74498-70b1-11e8-8c2f-e53c6e043628.png)
![2018-06-15_15 23 42](https://user-images.githubusercontent.com/22880199/41491967-0300df84-70b1-11e8-84fb-851f6fabb181.png)

**Comment by TheFloydman** [comment]
The <p> elements that are off-center are identical to the ones above and below them: <p align="center">.

**Comment by gigaherz** [comment]
Interesting... I'll be taking a look.

**Comment by gigaherz** [comment]
v2.6.0 is out! This issue should be fixed... I hope :P

**Comment by TheFloydman** [comment]
Looks great! Thank you!
