### ISSUE TITLE
Space Around In-line URLs

### ISSUE THREAD

**Issue by TheFloydman** [gigaherz/Guidebook#53]
When using `<link>` inside of a `<p>` element, it adds a space before and after the link. I don't know if this is intended or not, but I would rather it not add spaces. For example, when I add an in-line link, I would like this:

(link)

not this:

( link )

**Comment by gigaherz** [comment]
Hmm just to confirm, does your content look like
```xml
<p>Here is (<link ref="1:1">a link</link>)</p>
```
or
```xml
<p>Here is (
<link ref="1:1">a link</link>
)</p>
```

**Comment by TheFloydman** [comment]
In my case it's

<p align="center">{+<link ref="ch1:pageQuickGuide12">strBlock</link>} Obelisks</p>

This looks like

{+ strBlock } Obelisks

**Comment by gigaherz** [comment]
Okay then I have to fix that to match HTML better, since it makes more sense that way. :P

**Comment by gigaherz** [comment]
Had to tweak quite a few things, but next version will handle whitespace trimming a bit better :P

![image](https://user-images.githubusercontent.com/685851/41512905-149cf9b0-7293-11e8-83e1-fa6a868c179f.png)

Incidently, the alignment you mentioned in the other ticket seems to have fixed itself too...

![image](https://user-images.githubusercontent.com/685851/41512912-3c497024-7293-11e8-8a8e-4ff5b283178d.png)

**Comment by gigaherz** [comment]
v2.6.0 is out! Enjoy!
