### ISSUE TITLE
[Question] How can I use lang files for content of my guidebook?

### ISSUE THREAD

**Issue by KorDum** [gigaherz/Guidebook#57]
How can I use lang files for content of my guidebook?
I don't found in wiki.

**Comment by gigaherz** [comment]
I don't support using translation keys for content, yet. I implemented translations by having whole books in different langauges. Like, `bookname.es_es.xml`, `bookname.en_gb.xml` and such.
I can implement using translation keys, if people have an use for them, or prefer using that to populate the book contents...

**Comment by KorDum** [comment]
It is suitable, thanks!
