### ISSUE TITLE
No class definition gigaherz.common.ItemRegistered

### ISSUE THREAD

**Issue by KorDum** [gigaherz/Guidebook#58]
Hello! I was looking for a library to implement the guide, I stopped at your mod.
I added to build.gradle of my mod:
```
repositories {
    maven {
        url 'http://dogforce-games.com/maven'
    }
}
dependencies {
    deobfCompile "gigaherz.guidebook:Guidebook-1.12.2:2.6.0"
}
```

added handler:
```
@Optional.Method(modid="gbook")
@SubscribeEvent
public static void registerBook(BookRegistryEvent event) {
    event.register(ModResources.getResource("xml/guide.xml"));
}
```
added `dependencies = "after:gbook"` to main mod class. I do not think that I was wrong somewhere here.
Build mod and launch client... and crash:
https://gist.github.com/KorDum/7406297fb58ac7eff74fc856e51fcee1

Need some more core mod?
![image](https://user-images.githubusercontent.com/1331559/41780535-9f99d652-763d-11e8-834a-01c508119224.png)
Do you need any more information?

**Comment by gigaherz** [comment]
Hello, I think you have to add also another of my libraries:
```gradle
deobfCompile "gigaherz.commons:gigaherz.commons-1.12.1:0.6.4"
```
(Ignore the 1.12.1 part -- it works just fine on 1.12.2)

**Comment by KorDum** [comment]
Thanks for the answer! I'll try now.

**Comment by gigaherz** [comment]
The jar is embedded inside the guidebook jar, it is extracted on demand by forge's dependency extraction system. If you open the guidebook jar in winzip/winrar/7zip or whatever app you use, you'll see it's there inside META-INF/Libraries

**Comment by KorDum** [comment]
It's strange, why it does not happen when the client is launched through the IDE.

**Comment by gigaherz** [comment]
I do not really know why, sorry. I think it has to do with how forge works with embedded jars, but it's just a guess.
