### ISSUE TITLE
Bug with space between 2 cyrillic words

### ISSUE THREAD

**Issue by KorDum** [gigaherz/Guidebook#60]
Look:
![image](https://user-images.githubusercontent.com/1331559/41784103-62a6cc82-7647-11e8-9fa7-1e98c694eb18.png)

```
<link indent="10" ref="intro:1">ааааааа ббббббббббббб вввв</link>
<link indent="10" ref="intro:2">Сильные элементальные духи</link>
```
In xml 3 word in each link, but the last words are glued together. The problem is only visible when using a Unicode font. With English text all OK.

**Comment by gigaherz** [comment]
I'll take a look as soon as I can.

**Comment by KorDum** [comment]
Thanks!
I liked your mod. I would not like to look for another :)

**Comment by KorDum** [comment]
Font size = 1

**Comment by KorDum** [comment]
```
<book title="Demo / Feature test book" cover="gbook:demo" fontSize="1">
    <include ref="gbook:xml/standard.xml" />
    <chapter>
        <page>
            <link indent="10" ref="intro:1">ааааааа ббббббббббббб вввв</link>
            <link indent="10" ref="intro:2">Сильные элементальные духи</link>
        </page>
    </chapter>
</book>
```
This is full xml for bug.

**Comment by gigaherz** [comment]
I found the issue -- it is nothing to do with cyrillic! When I word-wrap texts, I was removing the space from the beginning of the world, so the next line would look right, but without that space, the measured size was not bigger than the line anymore, so it was placed in the same line, but without the sapce!

I will fix soon.

**Comment by gigaherz** [comment]
v2.6.5 has been uploaded to maven, and will be available in curseforge after it's reviewed. It should fix this.
