### ISSUE TITLE
Incorrect "Home" button behavior

### ISSUE THREAD

**Issue by KorDum** [gigaherz/Guidebook#61]
Guidebook 2.6.5

```xml
<book title="Demo / Feature test book" cover="gbook:demo" fontSize="1">
    <include ref="gbook:xml/standard.xml" />
    <chapter>
        <page>
            <title>Chapter 1:1</title>
        </page>
        <page>
            <title>Chapter 1:2</title>
        </page>
    </chapter>
    <chapter>
        <page>
            <title>Chapter 2:1</title>
        </page>
        <page>
            <title>Chapter 2:2</title>
        </page>
    </chapter>
    <chapter>
        <page>
            <title>Chapter 3:1</title>
        </page>
        <page>
            <title>Chapter 3:2</title>
        </page>
    </chapter>
</book>
```
And two bugs:
1. If I open book and click on "Home" button, I go to Chapter 2 instead Chapter 1.
2. If I click on "Home" twice+, I need to press the same number of times to go back.

**Comment by TheFloydman** [comment]
I'm not sure what's causing the issue, but try giving your chapters and pages IDs and adding `home="chapter1:page1"` to your book element, but use your own IDs, of course. What happens now?

**Comment by TheFloydman** [comment]
Whoops, I figured it out. The default behavior for the home button is to go to the second page of the second chapter. I have submitted a pull request to fix it. Using the "home" attribute in the "book" element should still work, though.

**Comment by gigaherz** [comment]
Merged that PR, will make a bugfix release soon.

**Comment by gigaherz** [comment]
Guidebook v2.7.0 has been uploaded to curseforge and is awaiting review. It includes the fix for this issue, among other changes.
