### ISSUE TITLE
Game Stage conditions don't work in multiplayer.

### ISSUE THREAD

**Issue by SuperKael** [gigaherz/Guidebook#66]
Simply as the title says. I am testing on my own dedicated server, and any element I tag with a game stage condition never appears. It works perfectly fine in singleplayer, just not in multiplayer. All of my configs are are the same on both my client and server, including the xml file containing the book.

Example that works in singleplayer, but not in multiplayer:

```
<book title="Test Guidebook">
	<conditions>
		<stage-unlocked name="test_stage" stage="test_stage" />
	</conditions>

        <chapter>
		<page id="Test Page 1" condition="test_stage">
			<title>Test Page 1</title>
		</page>
	</chapter>
	<chapter condition="test_stage">
		<page id="Test Page 2">
			<title>Test Page 2</title>
		</page>
	</chapter>
</book>
```

In singleplayer, both pages appear if and only if I have the test_stage. In multiplayer, neither of them appear regardless of whether or not I have the test_stage.

**Comment by gigaherz** [comment]
Hmmm I just tested, it works for me. What versions of Guidebook and GameStages are you using?

**Comment by gigaherz** [comment]
Seems I was using the client-side stages wrong.... Game Stages is a ... special API, it seems. It has different ways to access server-side data from client-side data, and I didn't realize that, so I was using the server-side method.

**Comment by SuperKael** [comment]
Wow, thanks! That was very fast! I submitted the issue just before heading to bed, and I wake up to find it fixed. Anyways, I just tested and confirmed that it's working now, thank you!
