### ISSUE TITLE
[Suggestion] NBT Support

### ISSUE THREAD

**Issue by Shazuli** [gigaherz/Guidebook#67]
***Hi!***

Certain mods create variants of similar working items by going by NBT data. [OpenComputers](https://minecraft.curseforge.com/projects/opencomputers) is a good example of that. They change the content as well as the appearance by changing the NBT of a storage device, so a NBT parameter in the stack tag would be nice (if it already exists in some way and I missed let me apologize in advance).

![4af0a4edc79560d1038ea4119d63f190](https://user-images.githubusercontent.com/9884180/43664630-d74ebb70-976d-11e8-8627-4ffce7edf9f3.gif)

**Comment by Necr0** [comment]
That's what the `tag`-attribute is for. You can have use it to add NBT in JSON format to the item. Keep in mind that you might have to escape the JSON to be able to use it as an XML attribute
```
<stack item="minecraft:coal" meta="0" count="1"  tag="{&quot;some_attribute&quot=&quot;some value&quot;}"
```
We should probably add it to the wiki at some point. There is quite a lack of documentation in general, unfortunately.

**Comment by Shazuli** [comment]
Thank you! Exactly what I'm looking for!
