### ISSUE TITLE
Crash while initializing game

### ISSUE THREAD

**Issue by danikk14g** [gigaherz/Guidebook#69]
Hello, i am doing some last tests before i release my modpack, so i have restarted Minecraft several times today, but now suddenly i get a crash, i dont think its because the book i made, last change i made was yesterday and it was fine, i just updated two mods (C&B and Plants2) today and made some config changes of other mods. I am using the last version (2.8.1), and last forge version (23.4.2750) here is the log:

https://pastebin.com/XC6vcHxy

Thank you.

**Comment by gigaherz** [comment]
Would it be possible for you to get a full debug log? the crash log doesn't include the "caused by" reasons of the crash, so I can't tell what is wrong with it...

**Comment by danikk14g** [comment]
File is too big for pastebin:

https://www101.zippyshare.com/v/E4sy1Q0b/file.html

**Comment by yuri0r** [comment]
facing the same issue may I add my debug.log aswell.

https://mega.nz/#!8Lw32JaI!7IxOcHHoNc3bhJ0qlG0iZXMuBOANO8FJH_uiOQVdKxU

**Comment by gigaherz** [comment]
2.8.2 is up on curseforge, awaiting review.

**Comment by gigaherz** [comment]
Apparently I wasn't the only one hit by this issue. Seems it's related to MultiMC. The fix is valid though, but not directly my fault. -- https://github.com/bdew/gendustry/issues/277

**Comment by danikk14g** [comment]
Now i get a crash from extrautils2 
Caused by: java.lang.NullPointerException
	at com.rwtema.extrautils2.book.BookHandler$1.func_110549_a(BookHandler.java:45)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
at com.rwtema.extrautils2.book.BookHandler.<clinit>(BookHandler.java:32)

I can put the full debug.log here but u said its not directly your fault, however i dont have (as far as i know) that mod you mention in my modpack :S

**Comment by gigaherz** [comment]
Yes that's just another mod hit by the same issue as mine, see their ticket: https://github.com/rwtema/Extra-Utilities-2-Source/issues/159

**Comment by yuri0r** [comment]
fixed it for me, thank you :)

**Comment by beanaboston** [comment]
Fixed it for me! Thanks, now just to figure out why rock hounding chemistry
is crashing. May be the same issue who knows.

**Comment by gigaherz** [comment]
It's actually a bug in forge, 2751 will fix it, once it's done going through CI and shows up in the files site. See: https://github.com/MinecraftForge/MinecraftForge/pull/5105

Mods are still at fault for assuming the returned value is not nullable, but the actual crash was revealed by mojang adding new languages that don't have an underscore in the name.

**Comment by beanaboston** [comment]
Thanks for the info.
