### ISSUE TITLE
external links in guidebook

### ISSUE THREAD

**Issue by PSILONCRAFT** [gigaherz/Guidebook#7]
what is the setup for external links in the guidebook
lets say I want to send players to my GitHub for bug reporting

**Comment by gigaherz** [comment]
I haven't coded that feature yet. Shouldn't take too long, though, so I'll try to write it later today.

**Comment by PSILONCRAFT** [comment]
Oh thats very nice

**Comment by PSILONCRAFT** [comment]
a mother thing if i want to use a custom image on front of the book where would i nest that image and what will the code be
 I have this code now

<book title="PSILONCRAFT MANUAL" cover="gbook:covers/default" fontSize="0.6">

but I want a nother png on the front that I will put in the /book folder i have my books in

**Comment by gigaherz** [comment]
The front cover can be changed in the book's root tag, along with the font size, and the book's title (the name that shows on the ingame item, like `<book title="Demo book" cover="gbook:demo" fontSize="0.6">`

"gbook:demo" will look for config/resources/textures/demo.png

**Comment by PSILONCRAFT** [comment]
thanks man

**Comment by PSILONCRAFT** [comment]
one last question about the confifile my book is called book1

what code do i have to use to give at first join?

# Configuration file

books {
    S:GiveOnFirstJoin <
     >
}


general {
    # -1 for same as GUI scale, 0 for auto, 1+ for small/medium/large
    I:BookGUIScale=0
}

**Comment by gigaherz** [comment]
the same book "id" that you use in the give command, like:
```
S:GiveOnFirstJoin <
    gbook:book1.xml
 >
```

**Comment by gigaherz** [comment]
Hello! v1.6.0 is out, and it adds external links: `<link href="http://github.com/gigaherz/Guidebook">Guidebook repository</link>`.

I'll consider this closed. :)

**Comment by Winddbourne** [comment]
I'd like to suggest we add an example using both GiveOnFirstJoin and the new code for external links both be added to a new example in the guidebook. This was a very helpful posting for me to read. :)

**Comment by PSILONCRAFT** [comment]
I´d also would like to suggest that you do an example with a jpeg or png picture swell. was a bit hard to understand the alignment with the xyz coords for a image in the guidebook.
what will a external link for a image look like?

**Comment by gigaherz** [comment]
@Winddbourne 
Ah yes, I meant to add it, but I forgot.

@PSILONCRAFT  
The ingame guidebook book has examples of using images: https://github.com/gigaherz/Guidebook/blob/master/src/main/resources/assets/gbook/xml/guidebook.xml

These have to be PNG images. The same restrictions apply to making images for resourcepacks. External images will not be supported. At least not any time soon.

If you mean make a clickable image link, that MIGHT be possible at some point in the future, but not right now.
