### ISSUE TITLE
2.8.2 broke both shapeless and shaped recipes

### ISSUE THREAD

**Issue by Yoghurt4C** [gigaherz/Guidebook#70]
![image](https://user-images.githubusercontent.com/11313954/44241664-055b3b00-a1ce-11e8-9730-53e5497c60ff.png)

**Comment by gigaherz** [comment]
o_O checking...

**Comment by gigaherz** [comment]
Oops. had a typo in a function. Still that's some crazy result to get from the tiny mistake I made :P

**Comment by Yoghurt4C** [comment]
the fire in the middle represents the current state of the mod :^)

**Comment by gigaherz** [comment]
v2.8.3 is up on curseforge awaiting review.
