### ISSUE TITLE
Guidebook feature

### ISSUE THREAD

**Issue by danikk14g** [gigaherz/Guidebook#79]
Hello, i am working on adding 50 or 100 challenges to my pack, some people wants a goal to work towards or they dont see a reason to go through it to the end. I was thinking how i could add them to the book,  i have read the Wiki and i haven't seen a way include them in any way. I had in mind using the crafting output for a checking mark or cross-lining a <p> by clicking a button. 
I may be asking about something impossible but i dont feel like adding a questbook mod only for the challenges when i can just make some pics to be placed in a wall with Bibliocraft painting.

Thanks.

**Comment by gigaherz** [comment]
Did you accidentally leave out part of the post? " cross-lining a [...?] by clicking a button." doesn't really compute.

If you only need the book to display the status of the challenges, and your challenges are set up to grant an advancement when they are completed, you could use advancement conditions to selectively display the checkmark. I don't know if this would work for you.
