### ISSUE TITLE
Latest Version (Guidebook-1.12.2-2.9.1.jar) Breaks GiveOnFirstJoin

### ISSUE THREAD

**Issue by jaxmacky** [gigaherz/Guidebook#85]
Guidebook-1.12.2-2.9.1.jar
forge-14.23.5.2838
MC 1.12.2

Latest version (Guidebook-1.12.2-2.9.1.jar) breaks GiveOnFirstJoin; no beginning book in inventory on first join.

Downgrading to Guidebook-1.12.2-2.8.3.jar fixes the issue.

**Comment by gigaherz** [comment]
I'll take a look, thanks for the report!

**Comment by gigaherz** [comment]
I can't reproduce in my development environment.

I set it to give me a couple books in the config,
![image](https://user-images.githubusercontent.com/685851/58376616-df3da500-7f6e-11e9-901f-415bb6216edd.png)

and they appeared in my inventory justfine after joining the world again,
![image](https://user-images.githubusercontent.com/685851/58376612-d1881f80-7f6e-11e9-89a3-f5c9a6f523a4.png)

Can you provide any more detail? Are there any errors in the log? Does it only happen in a dedicated server?

**Comment by jaxmacky** [comment]
Is that in game config new with (Guidebook-1.12.2-2.9.1.jar) ?

**Comment by gigaherz** [comment]
Yes, although I had it in my in-development code for many months before the latest release, so it's not "new" to me. XD

**Comment by gigaherz** [comment]
Oh this reminds me, I believe Forge doesn't delete old entries when configs are loaded, so there's a change you might have config values that are no longer relevant. 

The config file that I had after editing with the GUI was: 
```
# Configuration file

general {
    # Use -1 for same as GUI scale, 0 for auto, 1+ for small/medium/large
    # Min: -1
    # Max: 10
    I:bookGUIScale=0

    # Keep at false to use integral scaling, which makes the font pixels evently scaled. If set to true, the books will fill the screen space, even if the font becomes wonky.
    B:flexibleScale=false

    # List of books to give to the player when they join. Applied retroactively to existing players if a new book is added to the list.
    S:giveOnFirstJoin <
        gbook:book.xml
        gbook:bug.xml
     >
}
```

**Comment by jaxmacky** [comment]
I will test further, and report back. Been a long day already, so might be until tomorrow.  I'll try and delete the config, let it auto generate, and add the book after. I do thank you for the quick replies.

**Comment by jaxmacky** [comment]
Success!

-Removed Previous Config
-Updated Mod
-Start Pack/Generate New Config
-Add Book.xml to New Config
-Restart Pack
-Get Book in Hand!

Thank You!

**Comment by gigaherz** [comment]
Glad to hear. :)
