### ISSUE TITLE
Book GUI always displays at small scale

### ISSUE THREAD

**Issue by Matt-Sheridan** [gigaherz/Guidebook#9]
No matter how I scale the Minecraft interface or what I set the book GUI to in the mod config, the book always displays at what I figure is the minimum size. I'm using the Guidebook-1.10.2-1.6.0 release.

**Comment by LucidCypher** [comment]
I'm having the exact same problem.  :\

**Comment by Wissi** [comment]
Have you tried (in Minecraft settings) going to: 
Options 
Video Settings
and setting "GUI scale: **Auto**"

That seemed to work for me. Hope it helps.

**Comment by gigaherz** [comment]
There seems to be a bug with the "same as GUI scale" setting. Looking into it.

**Comment by gigaherz** [comment]
Nevermind, it's due to the book's choice of text scaling: A book with font size = 0.6, will have book scaling=1 on all 3 of small/medium/large, since 3*0.6=1.8 rounded down, is still 1. The solution is to manually specify a book scaling value 2/3/whatever in the config.
