### ISSUE TITLE
1.14.4 Forge

### ISSUE THREAD

**Issue by SepSol** [gigaherz/Guidebook#90]
Any plans for supporting Minecraft 1.14.4 (Forge)?

**Comment by gigaherz** [comment]
Yes, but I want to finish the new model loading system for forge first, so I can rely on that instead of hacks.

**Comment by SepSol** [comment]
Thanks a lot

**Comment by Giggitybyte** [comment]
Any progress on this? I'd love to have this for my 1.14.4 modpack.

**Comment by gigaherz** [comment]
I have gotten involved in the development of forge itself, and that has taken the majority of my free time. The plan still stands, I WILL finish porting this to 1.14.4 and 1.15.2 (I mean I'd say 1.15.1 but realistically, by the time I get around to it 1.15.2 will have been out for a while :P)

But just to show progress, this is the current status:

The book works (but relies on the new model system which isn't merged into 1.14.4 yet):
![image](https://user-images.githubusercontent.com/685851/72656627-f10c0680-399c-11ea-8bd5-70da335ea8a0.png)

Some features aren't quite working:
![image](https://user-images.githubusercontent.com/685851/72656632-fb2e0500-399c-11ea-9f3c-2f3583525ba3.png)

Some common recipe types aren't supported:
![image](https://user-images.githubusercontent.com/685851/72656645-0d0fa800-399d-11ea-92ee-d1c12bcb093a.png)

**Comment by Giggitybyte** [comment]
Sweet! Thank you for a status update; I'm glad to see you still plan on porting this.
I'll be checking in and waiting for your commits!
