### ISSUE TITLE
[1.15.2] Unrecognized tag: page-break

### ISSUE THREAD

**Issue by realTIMematrix** [gigaherz/Guidebook#91]
Hi,

i'm using MC 1.15.2, Forge 31.0.14 and your mod Guidebook-1.15.2-3.0.1.jar and i recognized the two following warnings in the logfile:

`[02Feb2020 23:15:34.069] [Server-Worker-4/WARN] [gbook/]: Unrecognized tag: page-break`
`[02Feb2020 23:15:34.073] [Server-Worker-4/WARN] [gbook/]: Unrecognized tag: page-break`

I know that you mentioned an issue in 1.15.2 but i don't know if this is the issue you are talking about.

**Comment by gigaherz** [comment]
Hmm curious. I'll look into it.
And no, the issue I mentioned is with cover images looking wrong in the inventory, if they contain semi-transparent pixels.

**Comment by gigaherz** [comment]
Oh! Oops. I used the wrong tag when updating the guidebook manual. You can safely ignore it, the warnings will be gone next version.
