### ISSUE TITLE
[1.12.2] Crash on Startup

### ISSUE THREAD

**Issue by vizthex123** [gigaherz/Guidebook#96]
Crash report attached, but the game crashes whenever I try to load it with v2.1.8 of the mod

Downgrading the version does nothing.

[crash-2020-07-20_14.18.45-client.txt](https://github.com/gigaherz/Guidebook/files/4949649/crash-2020-07-20_14.18.45-client.txt)

**Comment by gigaherz** [comment]
This crash isn't from "my" Guidebook, it's from a fork originally created by lirelent for internal use in other mods. Because the fork has modifications outside of my control, I can't provide support for it. I can't remember what mod was it used in, so I can't even point you in the right direction

**Comment by vizthex123** [comment]
Yeah I removed this mod and everything works fine. Not sure what caused it though, sorry.
