### ISSUE TITLE
Guidebook crashes while minecraft 1.16.1 is loading

### ISSUE THREAD

**Issue by ZariusCane** [gigaherz/Guidebook#97]
Forge-32.0.98

![guidebook](https://user-images.githubusercontent.com/16099481/89060241-4f407b80-d328-11ea-9ed2-12663f484dca.png)

**Comment by gigaherz** [comment]
Thanks for the report. I'll take a look.

**Comment by gigaherz** [comment]
3.1.2 should fix the issue.
